import { Inter } from "next/font/google";
import AuthProvider from "./context/AuthContext";
import ToasterContext from "./context/ToasterContext";
import "@/styles/globals.css";
import QueryProvider from "./context/QueryContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryProvider>
          <AuthProvider>
            <ToasterContext />
            <main className="main">{children}</main>
          </AuthProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
